### ISSUE TITLE
The extension does not work!

### ISSUE THREAD

**Issue by murugappanrm** [sudoaugustin/tailpile#2]
I tried the extension using the inadequate instruction. When i saved my test.tailwind.css  file, nothing happen. I think your documentation in here needs more clarity on how to use it.

**Comment by sudoaugustin** [comment]
Hello Murugappa, reloading vscode will solve this issue. And U will see this icon at the status bar.
![Group 2](https://user-images.githubusercontent.com/57541158/154223475-abf0066a-6724-456e-8bd7-3dd862494a7f.png)
I will make sure to add this in my next doc update.

**Comment by murugappanrm** [comment]
Hi Thank you for your assistance. I have decided to drop tailwindcss.clim and i decided to use CDN Version. When i imported the all the css library under ci, VSCode died trying search the whole lot of css it created. I tried looking for a solution in the net and found nothing.

**Comment by Lothindir** [comment]
Issue not resolved ! Juste set aside. Still doesn't work

**Comment by sudoaugustin** [comment]
@Lothindir  Can you attach an image or video?
